use crate::generator::GenerateOptions;

pub fn workspace_manifest(opts: &GenerateOptions) -> String {
    let (ecs_dep, ecs_feature) = if opts.ecs_stress {
        (
            r#"
bevy_ecs = { version = "0.15", optional = true }
"#,
            r#"
ecs-stress = ["bevy_ecs"]
"#,
        )
    } else {
        ("", "")
    };

    format!(
        r#"[package]
name = "stressgen-out"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[lib]
path = "src/lib.rs"

[dependencies]
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
clap = {{ version = "4", features = ["derive"] }}
async-trait = "0.1"
stress-macros = {{ path = "{macros_path}" }}
{ecs_dep}

[features]
default = []
{ecs_feature}
"#,
        macros_path = macros_path_relative(&opts.out_dir),
        ecs_dep = ecs_dep,
        ecs_feature = ecs_feature,
    )
}

fn macros_path_relative(out_dir: &std::path::Path) -> String {
    let manifest = std::path::PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".into()),
    );
    let macros = manifest.join("..").join("stress-macros");
    let macros = macros.canonicalize().unwrap_or(macros);
    let out = out_dir
        .canonicalize()
        .unwrap_or_else(|_| out_dir.to_path_buf());
    let rel = pathdiff(&out, &macros);
    if rel.is_empty() {
        "../../stress-macros".into()
    } else {
        rel
    }
}

fn pathdiff(from: &std::path::Path, to: &std::path::Path) -> String {
    pathdiff::diff_paths(to, from).replace('\\', "/")
}

pub fn root_lib(opts: &GenerateOptions) -> String {
    let ecs = if opts.ecs_stress {
        "\npub mod ecs_stress;\n"
    } else {
        ""
    };

    format!(
        r#"//! Auto-generated by stressgen — do not edit.

use clap::Parser;
use serde::{{Deserialize, Serialize}};
use async_trait::async_trait;

pub mod modules;
{ecs}

#[derive(Parser, Serialize, Deserialize)]
pub struct StressCli {{
    #[arg(long)]
    pub depth: usize,
}}

#[async_trait]
pub trait StressTrait: Send + Sync {{
    async fn run(&self) -> usize;
}}

pub struct StressNode<T: StressTrait> {{
    inner: T,
    next: Option<Box<StressNode<T>>>,
}}

impl<T: StressTrait> StressNode<T> {{
    pub fn depth(&self) -> usize {{
        1 + self.next.as_ref().map(|n| n.depth()).unwrap_or(0)
    }}
}}

stress_macros::generic_chain!({depth});

pub fn registry() -> usize {{
    let cli = StressCli {{ depth: {depth} }};
    let _ = modules::mod_00000::hot_path();
    cli.depth + std::mem::size_of::<Chain>()
}}
"#,
        depth = opts.intensity.scale_usize(16).clamp(4, 48),
    )
}

pub fn generated_module(index: usize, opts: &GenerateOptions) -> String {
    let depth = opts.intensity.scale_usize(8).clamp(2, 32);
    let trait_depth = (index % depth) + 1;

    format!(
        r#"//! Generated module {index}

use crate::{{StressCli, StressTrait, StressNode}};
use serde::{{Deserialize, Serialize}};

#[derive(Serialize, Deserialize)]
pub struct Entity{index} {{
    pub id: u64,
    pub payload: Vec<u8>,
}}

pub struct Worker{index};

#[async_trait::async_trait]
impl StressTrait for Worker{index} {{
    async fn run(&self) -> usize {{
        let _ = Entity{index} {{ id: {index} as u64, payload: vec![0; 128] }};
        {index}
    }}
}}

pub fn build_node() -> StressNode<Worker{index}> {{
    let mut node = StressNode {{
        inner: Worker{index},
        next: None,
    }};
    for _ in 0..{trait_depth} {{
        node = StressNode {{
            inner: Worker{index},
            next: Some(Box::new(node)),
        }};
    }}
    node
}}

#[stress_macros::stress_expand]
pub fn hot_path() -> usize {{
    let mut x = {index}usize;
    for _ in 0..64 {{
        x = x.wrapping_mul(1664525).wrapping_add(1013904223);
    }}
    x
}}
"#,
        index = index,
        trait_depth = trait_depth
    )
}

pub fn ecs_stress_module() -> &'static str {
    r#"//! Optional ECS-style compile stress (Bevy ECS).

use bevy_ecs::prelude::*;

#[derive(Component, Clone)]
pub struct StressComp(pub u64);

#[derive(Resource)]
pub struct StressRes(pub usize);

pub fn spawn_many(world: &mut World, count: usize) {
    for i in 0..count {
        world.spawn(StressComp(i as u64));
    }
}
"#
}

// Minimal inline path diff to avoid extra dependency in compile-stress lib.
mod pathdiff {
    use std::path::{Component, Path, PathBuf};

    pub fn diff_paths(path: &Path, base: &Path) -> String {
        let path = path.components().collect::<Vec<_>>();
        let base = base.components().collect::<Vec<_>>();
        let mut i = 0;
        while i < path.len() && i < base.len() && path[i] == base[i] {
            i += 1;
        }
        let mut out = PathBuf::new();
        for _ in i..base.len() {
            out.push("..");
        }
        for c in &path[i..] {
            if let Component::Normal(p) = c {
                out.push(p);
            }
        }
        if out.as_os_str().is_empty() {
            ".".into()
        } else {
            out.to_string_lossy().into_owned()
        }
    }
}
